import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { CASE_IDS, canonicalStringify, integer, runCase, sortedFacts, text, type GateInvocation, type ProbeInvocation } from "./packages/kernel/src/index.js"
interface ManifestFile { readonly path: string; readonly laneId: string; readonly moduleId: string | null; readonly packageId: string | null; readonly ownerRoleIds: Array<string>; readonly conceptIds: Array<string>; readonly centralBranchIds: Array<string> }
interface ManifestEdge { readonly id: string; readonly fromId: string; readonly toId: string; readonly kind: "static" | "type-only" | "dynamic" | "manifest" }
interface Manifest { files: Array<ManifestFile>; publicSurfaceIds: Array<string>; durableFormatIds: Array<string>; dependencyEdges: Array<ManifestEdge> }
interface Mutation { readonly action: string; readonly owner: string; readonly module: string; readonly pkg: string; readonly source: string; readonly branches?: ReadonlyArray<string>; readonly publicId?: string; readonly durableId?: string; readonly edge?: ManifestEdge }
const mutations: Record<string, Mutation> = {
  "P01-second-provider-instance": { action: "probe.add-second-provider-instance", owner: "role-first-party-provider-a", module: "module.provider-a-canary", pkg: "package.provider-a", source: "export const providerACanary = { id: \"provider-a-canary\", endpointClass: \"canary\" } as const\n" },
  "P02-packed-external-provider": { action: "probe.add-packed-external-provider", owner: "role-packed-external-provider", module: "module.external-secondary", pkg: "package.external", source: "export const externalSecondary = { packageName: \"@trial/external-provider\", instances: [\"primary\", \"secondary\"] } as const\nexport const consumeExternal = (instance: string): string => `external:${instance}`\n", edge: { id: "package.external->package.kernel:manifest", fromId: "package.external", toId: "package.kernel", kind: "manifest" } },
  "P03-new-first-party-provider": { action: "probe.add-first-party-provider", owner: "role-first-party-provider-c", module: "module.provider-c", pkg: "package.provider-c", source: "export const providerC = { id: \"provider-c\", instances: [{ id: \"provider-c-primary\" }], prepare: (requestId: string) => ({ requestId }) } as const\n", edge: { id: "package.provider-c->package.kernel:static", fromId: "package.provider-c", toId: "package.kernel", kind: "static" } },
  "P04-new-commitment-mechanism": { action: "probe.add-commitment-mechanism", owner: "role-machine", module: "module.delayed-commitment", pkg: "package.kernel", branches: ["branch.commitment"], source: "export type DelayedCommitment = { readonly authorityId: string; readonly notBefore: number }\nexport const authorizeDelayed = (authorityId: string, notBefore: number): DelayedCommitment => ({ authorityId, notBefore })\nexport const isReady = (revision: number, value: DelayedCommitment): boolean => revision >= value.notBefore\n" },
  "P05-existing-provider-operation": { action: "probe.add-existing-provider-operation", owner: "role-first-party-provider-a", module: "module.provider-a-reconcile", pkg: "package.provider-a", source: "export const reconcileProviderA = (operationId: string) => ({ _tag: \"ReconcileProviderA\" as const, operationId })\n" },
  "P06-journal-store-backend": { action: "probe.add-journal-store-backend", owner: "role-node-host", module: "module.memory-journal", pkg: "package.node-host", source: "export class MemoryJournal { readonly events: string[] = []; append(expected: number, event: string): boolean { if (expected !== this.events.length) return false; this.events.push(event); return true } }\n", edge: { id: "package.node-host->package.kernel:static", fromId: "package.node-host", toId: "package.kernel", kind: "static" } },
  "P07-file-tree-producer-adapter": { action: "probe.add-file-tree-producer-adapter", owner: "role-effect-build-adopter", module: "module.finalized-tree-v2", pkg: "package.effect-build-adopter", source: "export const adoptTreeV2 = (entries: ReadonlyArray<{ readonly name: string; readonly bytes: Uint8Array }>) => entries.map(entry => ({ ...entry, bytes: entry.bytes.slice() }))\n", edge: { id: "package.effect-build-adopter->package.kernel:static", fromId: "package.effect-build-adopter", toId: "package.kernel", kind: "static" } },
  "P08-deliberate-public-export": { action: "probe.add-public-export", owner: "role-surface-generator", module: "module.deliberate-export", pkg: "package.kernel", source: "export const deliberateTrialExport = { runtime: true, declaration: \"deliberateTrialExport\", emitted: true } as const\n", publicId: "public.trial-deliberate-export" },
  "P09-difficult-recovery-transition": { action: "probe.change-difficult-recovery", owner: "role-machine", module: "module.recovery-v2", pkg: "package.kernel", branches: ["branch.recovery"], source: "export interface RecoveryV2 { readonly schemaVersion: \"recovery-v2\"; readonly authorityId: string }\nexport const migrateRecoveryV1 = (authorityId: string): RecoveryV2 => ({ schemaVersion: \"recovery-v2\", authorityId })\n", durableId: "format.recovery-transition-v2" }
}
const compare = (a: string, b: string): number => a < b ? -1 : a > b ? 1 : 0
const runProbe = (input: ProbeInvocation) => {
  const mutation = mutations[input.probeId]
  if (mutation === undefined || input.changeDefinition.actionId !== mutation.action || input.changeDefinition.probeId !== input.probeId || input.changeDefinition.baseFixtureSha256 !== input.baseFixtureSha256) throw new Error("invalid probe binding")
  if (input.changeDefinition.requiredZeroTouchRoleIds.includes(mutation.owner)) throw new Error("protected role touched")
  mkdirSync("probe-changes", { recursive: true }); const path = `probe-changes/${input.probeId.toLowerCase()}.ts`; writeFileSync(path, mutation.source, { encoding: "utf8", mode: 0o644, flag: "wx" })
  const manifest = JSON.parse(readFileSync("trial-candidate.json", "utf8")) as Manifest
  manifest.files.push({ path, laneId: "product-source", moduleId: mutation.module, packageId: mutation.pkg, ownerRoleIds: [mutation.owner], conceptIds: [input.probeId === "P04-new-commitment-mechanism" || input.probeId === "P09-difficult-recovery-transition" ? "concept.difficult-path" : "concept.main-path"], centralBranchIds: [...(mutation.branches ?? [])] })
  if (mutation.publicId !== undefined) manifest.publicSurfaceIds.push(mutation.publicId); if (mutation.durableId !== undefined) manifest.durableFormatIds.push(mutation.durableId); if (mutation.edge !== undefined && !manifest.dependencyEdges.some(({ id }) => id === mutation.edge!.id)) manifest.dependencyEdges.push(mutation.edge)
  manifest.files.sort((a, b) => compare(a.path, b.path)); manifest.publicSurfaceIds.sort(compare); manifest.durableFormatIds.sort(compare); manifest.dependencyEdges.sort((a, b) => compare(a.id, b.id)); writeFileSync("trial-candidate.json", canonicalStringify(manifest), "utf8")
  return { schemaVersion: "architecture-probe-observation-v2", runContextSha256: input.runContextSha256, candidateId: input.candidateId, candidateTreeSha256: input.candidateTreeSha256, definitionSha256: input.definitionSha256, probeId: input.probeId, baseFixtureSha256: input.baseFixtureSha256, changeDefinitionSha256: input.changeDefinitionSha256, changeId: input.changeDefinition.changeId, facts: sortedFacts([["probe.observed-change", text(input.probeId)], ...input.changeDefinition.requiredChangeKinds.map((kind) => [`change-kind.${kind}.path`, text(path)] as const)]) }
}
const runGate = (input: GateInvocation) => ({ schemaVersion: "architecture-gate-observation-v2", runContextSha256: input.runContextSha256, candidateId: input.candidateId, candidateTreeSha256: input.candidateTreeSha256, definitionSha256: input.definitionSha256, gateId: input.gateId, facts: sortedFacts([["gate.candidate-local-conformance", text("passed")], ["gate.supported-case-count", integer(CASE_IDS.length)], ["gate.supported-probe-count", integer(9)]]) })
const mode = process.argv[2]; const input = JSON.parse(readFileSync(0, "utf8")) as any; const output = mode === "case" ? runCase(input) : mode === "probe" ? runProbe(input) : mode === "gate" ? runGate(input) : (() => { throw new Error(`unsupported mode ${String(mode)}`) })(); process.stdout.write(canonicalStringify(output))
