// Canonical checked-in Action bundle. Minification removes dependency-path
// comments whose spelling varies between Bun's workspace and clean offline
// install layouts. The final whitespace normalization keeps generated bytes
// acceptable to `git diff --check`, including whitespace inside dependency
// template literals.
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join, relative } from "node:path"
import { exit } from "node:process"

const root = join(import.meta.dir, "..")
export const actionBundleEntryPath = join(root, "apps", "ts-release-action", "src", "index.ts")
export const actionBundlePath = join(root, "apps", "ts-release-action", "dist", "index.js")
export const actionLauncherEntryPath = join(root, "apps", "ts-release-action", "src", "launcher-main.ts")
export const actionLauncherPath = join(root, "apps", "ts-release-action", "dist", "launcher.cjs")
export const actionArtifactBridgeEntryPath = join(root, "apps", "ts-release-action", "src", "artifact-bridge-main.ts")
export const actionArtifactBridgePath = join(root, "apps", "ts-release-action", "dist", "artifact-bridge.cjs")
export const actionReportRetainerEntryPath = join(root, "apps", "ts-release-action", "src", "report-retainer-main.ts")
export const actionReportRetainerPath = join(root, "apps", "ts-release-action", "report-retainer", "dist", "index.cjs")
export const actionReportHandoffEntryPath = join(root, "apps", "ts-release-action", "src", "report-handoff-main.ts")
export const actionReportHandoffPath = join(root, "apps", "ts-release-action", "report-handoff", "dist", "index.cjs")

export const buildActionBundle = async (outputPath: string = actionBundlePath): Promise<void> => {
  const built = await Bun.build({
    entrypoints: [actionBundleEntryPath],
    target: "node",
    format: "esm",
    minify: true
  })
  if (!built.success || built.outputs[0] === undefined) {
    throw new Error([
      "Action bundle build failed.",
      ...built.logs.map((entry) => String(entry))
    ].join("\n"))
  }
  const canonical = (await built.outputs[0].text()).replace(/[ \t]+$/gmu, "")
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, canonical)
}

export const buildActionLauncher = async (outputPath: string = actionLauncherPath): Promise<void> => {
  const built = await Bun.build({
    entrypoints: [actionLauncherEntryPath],
    target: "node",
    format: "cjs",
    minify: true
  })
  if (!built.success || built.outputs[0] === undefined) {
    throw new Error([
      "Action launcher build failed.",
      ...built.logs.map((entry) => String(entry))
    ].join("\n"))
  }
  const canonical = (await built.outputs[0].text()).replace(/[ \t]+$/gmu, "")
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, canonical)
}

export const buildActionArtifactBridge = async (outputPath: string = actionArtifactBridgePath): Promise<void> => {
  const built = await Bun.build({
    entrypoints: [actionArtifactBridgeEntryPath],
    target: "node",
    format: "cjs",
    minify: true
  })
  if (!built.success || built.outputs[0] === undefined) {
    throw new Error([
      "Action artifact bridge build failed.",
      ...built.logs.map((entry) => String(entry))
    ].join("\n"))
  }
  const canonical = (await built.outputs[0].text()).replace(/[ \t]+$/gmu, "")
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, canonical)
}

export const buildActionReportRetainer = async (outputPath: string = actionReportRetainerPath): Promise<void> => {
  const built = await Bun.build({
    entrypoints: [actionReportRetainerEntryPath],
    target: "node",
    format: "cjs",
    minify: true
  })
  if (!built.success || built.outputs[0] === undefined) {
    throw new Error([
      "Action report-retainer build failed.",
      ...built.logs.map((entry) => String(entry))
    ].join("\n"))
  }
  const canonical = (await built.outputs[0].text()).replace(/[ \t]+$/gmu, "")
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, canonical)
}

export const buildActionReportHandoff = async (outputPath: string = actionReportHandoffPath): Promise<void> => {
  const built = await Bun.build({
    entrypoints: [actionReportHandoffEntryPath],
    target: "node",
    format: "cjs",
    minify: true
  })
  if (!built.success || built.outputs[0] === undefined) {
    throw new Error([
      "Action report-handoff build failed.",
      ...built.logs.map((entry) => String(entry))
    ].join("\n"))
  }
  const canonical = (await built.outputs[0].text()).replace(/[ \t]+$/gmu, "")
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, canonical)
}

if (import.meta.main) {
  try {
    await buildActionBundle()
    await buildActionLauncher()
    await buildActionArtifactBridge()
    await buildActionReportRetainer()
    await buildActionReportHandoff()
    console.log(`Built ${relative(root, actionBundlePath)} from ${relative(root, actionBundleEntryPath)}.`)
    console.log(`Built ${relative(root, actionLauncherPath)} from ${relative(root, actionLauncherEntryPath)}.`)
    console.log(`Built ${relative(root, actionArtifactBridgePath)} from ${relative(root, actionArtifactBridgeEntryPath)}.`)
    console.log(`Built ${relative(root, actionReportRetainerPath)} from ${relative(root, actionReportRetainerEntryPath)}.`)
    console.log(`Built ${relative(root, actionReportHandoffPath)} from ${relative(root, actionReportHandoffEntryPath)}.`)
  } catch (cause) {
    console.error(cause instanceof Error ? cause.message : String(cause))
    exit(1)
  }
}
