// Canonical checked-in Action bundle. Minification removes dependency-path
// comments whose spelling varies between Bun's workspace and clean offline
// install layouts. The final whitespace normalization keeps generated bytes
// acceptable to `git diff --check`, including whitespace inside dependency
// template literals.
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join, relative } from "node:path"
import { exit } from "node:process"

const root = join(import.meta.dir, "..")
export const actionBundleEntryPath = join(root, "apps", "ts-release-action", "src", "index.ts")
export const actionBundlePath = join(root, "apps", "ts-release-action", "dist", "index.js")

export const buildActionBundle = async (outputPath: string = actionBundlePath): Promise<void> => {
  const built = await Bun.build({
    entrypoints: [actionBundleEntryPath],
    target: "node",
    format: "esm",
    minify: true
  })
  if (!built.success || built.outputs[0] === undefined) {
    throw new Error([
      "Action bundle build failed.",
      ...built.logs.map((entry) => String(entry))
    ].join("\n"))
  }
  const canonical = (await built.outputs[0].text()).replace(/[ \t]+$/gmu, "")
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, canonical)
}

if (import.meta.main) {
  try {
    await buildActionBundle()
    console.log(`Built ${relative(root, actionBundlePath)} from ${relative(root, actionBundleEntryPath)}.`)
  } catch (cause) {
    console.error(cause instanceof Error ? cause.message : String(cause))
    exit(1)
  }
}
