import * as Effect from "effect/Effect";
import { JournalEvent, LabError } from "../machine/src/contracts.js";
export declare const EVENT_BYTES = 1048576;
export declare const encoder: TextEncoder;
export declare const fail: (code: string, message: string) => never;
export declare const caught: (error: unknown) => LabError;
export declare const attempt: <A>(name: string, body: () => A) => Effect.Effect<A, LabError, never>;
export declare const eventBytes: (event: JournalEvent) => Uint8Array<ArrayBuffer>;
export declare function readEvent(bytes: Uint8Array, limit?: number): JournalEvent;
export declare function body(event: JournalEvent, journalId: string, limit: number): string;
