import { readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
const directory = resolve(import.meta.dir, "../../docs/refactor/architecture-program")
const input = JSON.parse(readFileSync(`${directory}/inputs/research-traceability.json`, "utf8"))
const waveByStep: Record<string,string> = {"is.01-kernel":"W01","is.02-npm":"W02","is.03-warehouse":"W03","is.04-core-transports":"W04","is.05-github":"W05","is.06-catalog-git":"W06","is.07-custom-provider":"W07","is.08-artifacts":"W08","is.09-ai-native":"W09","is.10-action-self-release":"W10"}
const decisions: Record<string, {status:string; decision:string; evidence:string[]}> = {
  "final-provider-typescript-spelling": {status:"design-specified",decision:"ProviderDescriptor is the service-free three-field durable minimum; ProviderDefinition adds actual runtime/native boundaries. Metadata-only authoring need not construct a runtime provider.",evidence:["kernel-api.d.ts","machine.md"]},
  "application-trusted-nonstructural-law": {status:"deferred",decision:"No application-declared nonstructural automatic replay in the first implementation. Opaque effects stop Inconclusive after ambiguous sends.",evidence:["machine.md"]},
  "shared-remote-journal-ux": {status:"design-specified-deployment-unqualified",decision:"Explicit JournalStore composition; Bun local SQLite default only. Action requires a configured shared store and exact deployment qualification; no automatic Git-ref default.",evidence:["hosts.md","qualification.md"]},
  "git-ref-journal": {status:"locally-proved-deployment-unqualified",decision:"Append-only per-journal ref, global expected revision and exact event identity. Local bare repository tests prove storage mechanics; repository permissions/rules/retention remain hosted qualification.",evidence:["hosts.md","qualification.md"]},
  "filesystem-generation-portability": {status:"deferred",decision:"No portable filesystem-generation default or parallel production store. Archive donor as evidence; implement only after future conformance demand.",evidence:["hosts.md","migration.json"]},
  "s3-journal": {status:"locally-proved-upstream-scope-superseded",decision:"Optional general backend. Historical effect-build release-readiness selection was superseded by immutable PR37/Plan045 npm-only scope; Apple/AWS are explicitly deferred there. Preserve optional S3 version-addressed events plus conditional head CAS and future deployment qualification without reviving the obsolete upstream gate.",evidence:["hosts.md","qualification.md"]},
  "apple-commit-before-id-correlation": {status:"locally-proved-native-qualification-pending",decision:"Native SubmissionOutcomeUnknown survives in sole journal; stop Inconclusive before recorded submission identity. No inferred remote absence, resubmit, polling-by-guessed-ID or false correlation.",evidence:["apple-adoption.md","machine.md"]},
  "request-fingerprint-canonicalization": {status:"locally-proved",decision:"Strict canonical public request facts with endpoint/method/nonsecret headers/principal/scope/transport/body SHA256 and decimal byte count; private copied body verified before sending. Native replay law remains separate.",evidence:["machine.md","kernel-api.d.ts"]},
  "receipt-observation-schema-migration": {status:"design-specified-and-extension-tested",decision:"Exact versioned native codecs; unknown/mismatched old formats fail closed. User-authorized hard cut has no compatibility reader. P09 one-shot exact-source migration is research proof, not a shipped general migration API.",evidence:["machine.md","migration.json"]},
  "effect-build-compatible-effect-migration": {status:"resolved-at-new-coordinate",decision:"Aligned Effect 4.0.0-rc.108 and actual published effect-build0.6.3 strict Node/Bun consumers replace historical beta.83/private-comparator classification. Published ts-release0.3.0 still has beta.83 peers; it is a separate hard-cut donor, not the new target. The proposed API and actual producer consumers now pass against official unpatched rc.108; omit patchedDependencies in the future manifests. Preserve the existing donor patch until the authorized hard cut; current production source was not changed.",evidence:["upstream.md","apple-adoption.md","public-history.md","qualification.md"]},
  "h3-resolved-artifact-handle": {status:"locally-proved",decision:"Owned Content (decimal byte length, SHA256) plus logical File/Tree metadata; native producer paths are transient. Copy/verify before immutable finalization and verify again on durable loading.",evidence:["apple-adoption.md"]},
  "artifact-kernel-package-extraction": {status:"deferred",decision:"No third shared artifact package. ts-release owns adoption; existing effect-build public values are the producer boundary. New required upstream source is zero for admitted streaming-file/bounded-tree capability.",evidence:["apple-adoption.md","layout.json"]},
  "github-tag-default-policy": {status:"design-specified",decision:"Require an explicit Lightweight or Annotated tag choice. No silent default. Annotated intent binds its complete native tag object fields and commit.",evidence:["provider-api.md"]},
  "catalog-renderer-package-owner": {status:"design-specified",decision:"Homebrew and Scoop each own native rendering; common conditional Git owns exact multi-file native object construction and ref mutation. No provider sibling dependency.",evidence:["provider-api.md","layout.json"]},
  "msix-production-credential-backend": {status:"native-qualification-pending",decision:"Preserve selected SignTool Authenticode mechanics through actual upstream API. Credential source is explicit host composition and is qualified on the Windows witness; no signing service or credential vault is added to release core.",evidence:["qualification.md","apple-adoption.md"]}
}
const overrides:Record<string,{status:string;decision:string;evidence:string[]}> = {
  "effect-beta83-first-slice": decisions["effect-build-compatible-effect-migration"]!,
  "rc108-production-authority": decisions["effect-build-compatible-effect-migration"]!,
  "provider-optional-operations": {status:"retained-with-exact-spelling",decision:"ProviderDescriptor supports metadata-only authoring; executable ProviderDefinition supplies preparation/native receipt laws and optional observation/error boundaries. Correction is ordinary new operations, not a universal workflow.",evidence:["kernel-api.d.ts","provider-api.md"]},
  "replay-vocabulary": {status:"retained-first-slice-subset",decision:"Versioned vocabulary remains extensible. Only None and structurally witnessed core Git compare-and-swap are admitted now; IdempotencyKey/ExactDuplicateAccepted are not speculative runtime constructors.",evidence:["machine.md"]},
  "journal-store-law": {status:"retained-with-exact-spelling",decision:"JournalStore.append(journalId, expectedRevision, event) implements the retained appendIfRevision law; AlreadyRecorded is not a new dispatch permit.",evidence:["kernel-api.d.ts","hosts.md"]}
}
const rows = input.propositions.map((p:any) => {
  const key=p.id.replace(/^pr21\.proposition\./,"")
  const original={class:p.class,disposition:p.disposition,currentStatus:p.currentStatus,sourceRecordId:p.sourceRecordId,productAuthority:p.productAuthority,sourceCoordinates:p.sourceCoordinates}
  if(p.class==="product-outcome") {
    const waves=p.successorIds.map((id:string)=>{const wave=waveByStep[id];if(!wave)throw new Error(`Missing wave ${p.id}:${id}`);return wave})
    return {id:p.id,proposition:p.proposition,original,status:"selected-implementation-and-acceptance-required",scopeChanged:false,waves,ownerIds:p.ownerIds,requiredWitnessKinds:p.requiredWitnessKinds,evidence:["provider-api.md","qualification.md","waves.md"],decision:"Preserve this exact selected outcome. Local architecture experiments do not close its live/product acceptance witnesses."}
  }
  const resolution=overrides[key]??decisions[key]
  if(p.class==="deferred-seam"&&!resolution)throw new Error(`Unresolved seam ${p.id}`)
  if(resolution)return {id:p.id,proposition:p.proposition,original,...resolution}
  const status=({"later-outcome":"later-not-selected","maintained-destination":"future-provider-not-selected","rejected-candidate":"rejected-retained","census-disposition":"census-disposition-retained","research-law":"retained-design-law","historical-lesson":"retained-research-lesson","historical-api":"hard-cut-no-alias","historical-format":"archive-no-target-reader","historical-metric":"historical-not-current-denominator","historical-topology":"candidate-not-prior-selection"} as Record<string,string>)[p.class]
  if(!status)throw new Error(`Unhandled proposition class ${p.class}`)
  return {id:p.id,proposition:p.proposition,original,status,decision:p.class==="historical-format"?"User authorized hard cut; retain original payload bytes as archival evidence, no automatic deletion or dual reader.":"Preserve original disposition at its stated evidence level; no implied addition to the 69 selected outcomes.",evidence:[p.class.startsWith("historical-")?"research-lineage.md":"qualification.md"]}
})
if(rows.length!==226||rows.filter((row:any)=>row.original.class==="product-outcome").length!==69)throw new Error("Scope denominator changed")
const result={format:"ts-release/architecture-reconciliation/1",source:"../inputs/research-traceability.json",policy:"Original decisions remain immutable provenance. Resolutions explicitly identify a later coordinate or narrower evidence claim; no local experiment is promoted to live product acceptance.",counts:Object.fromEntries([...new Set(rows.map((row:any)=>row.original.class))].map(c=>[c,rows.filter((row:any)=>row.original.class===c).length])),rows}
const encoded=JSON.stringify(result,null,2)+"\n",path=`${directory}/handoff/reconciliation.json`
if(process.argv.includes("--check")){if(readFileSync(path,"utf8")!==encoded)throw new Error("Reconciliation is stale")}else writeFileSync(path,encoded)
console.log(JSON.stringify({propositions:rows.length,selected:69,resolvedSeams:15,coordinateOverrides:Object.keys(overrides)}))
